version: '3.8'
services:
  postgresqldb:
    container_name: POSTGRESQL
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: dockersd
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    networks:
      - netadrian
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jaeger:
    container_name: JAEGER-ADRYP
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 14268:14268

    networks:
      - netadrian

  app:
    container_name: SPRING-ADRYP
    depends_on:
      - postgresqldb
#    image: adrianc47/spring-adry-postgresql:latest
    image: spring-adryp
    build: .
    links:
      - jaeger
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/dockersd
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - JAEGER_HOST=jaeger

    networks:
      - netadrian
networks:
  netadrian:
    driver: bridge

